/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deliveryproject;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*;

/**
 *
 * @author User
 */
public class InputTrackingIdGUI extends javax.swing.JFrame {

    /**
     * Creates new form InputTrackingGUI
     */
    public InputTrackingIdGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        trackingIDField1 = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tracking ID :");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        trackingIDField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trackingIDField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackingIDField1ActionPerformed(evt);
            }
        });

        searchButton1.setText("Back");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(searchButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel16)
                .addGap(26, 26, 26)
                .addComponent(trackingIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(trackingIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    // ดึงข้อมูลจากไฟล์ record.txt และทำการค้นหา
    List<JPanel> resultPanels = searchData();

    // แสดงผลลัพธ์
    if (!resultPanels.isEmpty()) {
        for (JPanel resultPanel : resultPanels) {
            JOptionPane.showOptionDialog(
                    this,
                    resultPanel,
                    "Search Results",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    new Object[]{},
                    null
            );
        }
    } else {
        JOptionPane.showMessageDialog(this, "No records found", "Search Results", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_searchButtonActionPerformed

private JPanel createResultPanel(String[] parts) {
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

    // Display information
    panel.add(new JLabel("----------"));
    panel.add(new JLabel("Tracking ID : " + parts[0]));
    panel.add(new JLabel("Sender Name : " + parts[1]));
    panel.add(new JLabel("Sender Address : " + parts[2]));
    panel.add(new JLabel("Receiver Name : " + parts[4]));
    panel.add(new JLabel("Receiver Address : " + parts[5]));
    panel.add(new JLabel("Status : " + parts[10]));
    panel.add(new JLabel("Timestamp : " + parts[11]));

    // Add a button for updating status
    JButton updateStatusButton = new JButton("Update Status");
    updateStatusButton.addActionListener(e -> {
        String newStatus = JOptionPane.showInputDialog(this, "Enter new status:");
        if (newStatus != null && !newStatus.trim().isEmpty()) {
            // TODO: Update the status in your data structure or file
            // For now, just display the new status
            JOptionPane.showMessageDialog(this, "Status updated to: " + newStatus);
        }
    });
    panel.add(updateStatusButton);

    return panel;
}

private List<JPanel> searchData() {
    List<JPanel> resultPanels = new ArrayList<>();
    String searchTrackingID = trackingIDField1.getText();
    String filePath = "D:\\CSC250\\Delivery project\\src\\main\\java\\db\\record.txt";

    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            String trackingID = parts[0];

            // Check if Tracking ID matches (if provided)
            boolean trackingIDMatch = trackingID.equals(searchTrackingID);
            if (trackingIDMatch) {
                resultPanels.add(createResultPanel(parts));
            }
        }
    } catch (IOException ioException) {
        ioException.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading/writing to the file", "Error", JOptionPane.ERROR_MESSAGE);
    }

    return resultPanels;
}


    
    private void trackingIDField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingIDField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackingIDField1ActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
         //open input tracking
        setVisible(false);
        RoleGUI ob = new RoleGUI();
        ob.setVisible(true);
    }//GEN-LAST:event_searchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTrackingIdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTrackingIdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTrackingIdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTrackingIdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputTrackingIdGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField trackingIDField1;
    // End of variables declaration//GEN-END:variables
}
