/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deliveryproject;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Random;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.io.File;


/**
 *
 * @author User
 */
public class UserGUI extends javax.swing.JFrame {
private Date timeStamp;
    /**
     * Creates new form MainGUI
     */
    public UserGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(525, 335));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delivery Program");
        jLabel1.setToolTipText("");

        addButton.setText("Add Parcel");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Tracking");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
         // Create a Random object
        Random random = new Random();

        // Generate a random integer between 1 and 100 (inclusive)
        int min = 1;
        int max = 1000000;
        int randomInRange = random.nextInt(max - min + 1) + min;
                
                //JTextField trackingIDField = new JTextField();
                JTextField senderNameField = new JTextField();
                JTextField senderAddressField = new JTextField();
                JTextField senderPhoneNumberField = new JTextField();
                JTextField receiverNameField = new JTextField();
                JTextField receiverAddressField = new JTextField();
                JTextField receiverPhoneNumberField = new JTextField();
                JTextField contentField = new JTextField();
                JTextField weightField = new JTextField();
                JCheckBox perishableCheckbox = new JCheckBox("is Fresh");

                JPanel panel = new JPanel();
                panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                //panel.add(new JLabel("Tracking ID:"));
               // panel.add(trackingIDField);
                panel.add(new JLabel("Sender Name:"));
                panel.add(senderNameField);
                panel.add(new JLabel("Sender Address:"));
                panel.add(senderAddressField);
                panel.add(new JLabel("Sender Phone Number:"));
                panel.add(senderPhoneNumberField);
                panel.add(new JLabel("Receiver Name:"));
                panel.add(receiverNameField);
                panel.add(new JLabel("Receiver Address:"));
                panel.add(receiverAddressField);
                panel.add(new JLabel("Receiver Phone Number:"));
                panel.add(receiverPhoneNumberField);
                panel.add(new JLabel("Parcel Content:"));
                panel.add(contentField);
                panel.add(new JLabel("Weight (kg):"));
                panel.add(weightField);
                panel.add(perishableCheckbox);

                int result = JOptionPane.showConfirmDialog(null, panel,
                        "Enter Parcel Information", JOptionPane.OK_CANCEL_OPTION);
                     
                if (result == JOptionPane.OK_OPTION) {
                    // Extract input values and create a new Parcel object
                    String trackingID = randomInRange+"";
                   
                    String senderName = senderNameField.getText();
                    String senderAddress = senderAddressField.getText();
                    String senderPhoneNumber = senderPhoneNumberField.getText();
                    String receiverName = receiverNameField.getText();
                    String receiverAddress = receiverAddressField.getText();
                    String receiverPhoneNumber = receiverPhoneNumberField.getText();
                    String content = contentField.getText();
                    double weight = Double.parseDouble(weightField.getText());
                    //boolean isFresh = false;
                    LocalDate currentDate = LocalDate.now();
                    Sender newSender = new Sender(senderName, senderAddress, senderPhoneNumber);
                    Recipient newRecipient = new Recipient(receiverName, receiverAddress, receiverPhoneNumber);
                     // Get the current date and time using LocalDateTime
                        LocalDate currentDateTime = LocalDate.now();

                        // Convert LocalDateTime to Date
                        timeStamp = java.sql.Date.valueOf(currentDateTime);
                    if(perishableCheckbox.isSelected()){
                        Fresh newFresh = new Fresh(weight, content);
                        DeliveryService newDeliveryService = new DeliveryService(trackingID,newSender, newRecipient, newFresh, timeStamp,"In Transit");
                    }else{
                        Dry newDry = new Dry(weight, content);
                        DeliveryService newDeliveryService = new DeliveryService(trackingID,newSender, newRecipient, newDry,timeStamp,"In Transit");
                    }
                 JOptionPane.showMessageDialog(this, "Your Parcel tracking ID:"+trackingID+"\nTime:"+timeStamp);
                 
                 //add id checking
            }
                //JOptionPane.showMessageDialog(this, "Your Parcel tracking ID:"+trackingID);
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //open input tracking
        setVisible(false);
        InputTrackingGUI ob = new InputTrackingGUI();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
